
def read_vtk_to_mesh(filename):
    nodes = []
    triangles = []
    
    with open(filename, 'r') as f:
        lines = f.readlines()
        i = 0
    
        while i < len(lines):
            line = lines[i].strip()
            
            if line.startswith("POINTS"):
                
                num_nodes = int(line.split()[1])
                i += 1
                for _ in range(num_nodes):
                    node = list(map(float, lines[i].split()))
                    nodes.append(tuple(node))
                    i += 1
                    
            elif line.startswith("CELLS"):
                
                parts = line.split()
                num_cells = int(parts[1])
                i += 1
                for _ in range(num_cells):
                    cell_data = list(map(int, lines[i].split()))
                    if cell_data[0] == 3:  
                        triangles.append(cell_data[1:4])
                    i += 1
                    
            elif line.startswith("CELL_TYPES"):
               
                num_types = int(line.split()[1])
                i += num_types + 1
                
            else:
                i += 1
    print(f"Have read {len(nodes)} nodes and {len(triangles)} triangles from {filename}...")
    return nodes, triangles



def write_mesh_to_vtk(nodes,triangles,labels,filename,minus_one=True):
    with open(filename, 'w') as f:
        
        f.write("# vtk DataFile Version 2.0\n")
        f.write("Generated by CAD mesh processing\n")
        f.write("ASCII\n")
        f.write("DATASET UNSTRUCTURED_GRID\n\n")
        
        f.write(f"POINTS {len(nodes)} float\n")
        for node in nodes:
            f.write(f"{node[0]} {node[1]} {node[2]}\n")
        f.write("\n")
        
        
        f.write(f"CELLS {len(triangles)} {len(triangles) * 4}\n")
        for tri in triangles:
            if minus_one:
                f.write(f"3 {tri[0]-1} {tri[1]-1} {tri[2]-1}\n")  
            else:
                f.write(f"3 {tri[0]} {tri[1]} {tri[2]}\n")  
        f.write("\n")
        
        
        f.write(f"CELL_TYPES {len(triangles)}\n")
        for _ in triangles:
            f.write("5\n")  
        f.write("\n")
        
        f.write(f"CELL_DATA {len(triangles)}\n")
        f.write("SCALARS labels int 1\n")
        f.write("LOOKUP_TABLE default\n")
        for label in labels:
            f.write(f"{label}\n")
        
        
    print(f"The new mesh has been written to {filename}!")
    

def write_mesh_to_vtk_v2(nodes,triangles,filename,minus_one=True):
    with open(filename, 'w') as f:
        
        f.write("# vtk DataFile Version 2.0\n")
        f.write("Generated by CAD mesh processing\n")
        f.write("ASCII\n")
        f.write("DATASET UNSTRUCTURED_GRID\n\n")
        
        f.write(f"POINTS {len(nodes)} float\n")
        for node in nodes:
            f.write(f"{node[0]} {node[1]} {node[2]}\n")
        f.write("\n")
        
        
        f.write(f"CELLS {len(triangles)} {len(triangles) * 4}\n")
        for tri in triangles:
            if minus_one:
                f.write(f"3 {tri[0]-1} {tri[1]-1} {tri[2]-1}\n")  
            else:
                f.write(f"3 {tri[0]} {tri[1]} {tri[2]}\n")  
        f.write("\n")
        
        
        f.write(f"CELL_TYPES {len(triangles)}\n")
        for _ in triangles:
            f.write("5\n")  
    print(f"The new mesh has been written to {filename}!")
    
